# Generated by Django 5.2.4 on 2025-07-31 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['emp_id']},
        ),
    ]
