# Generated by Django 5.2.4 on 2025-07-25 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_brach_student_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id']},
        ),
    ]
